// Fin-Lumen v29.1
// Legacy recommendation engine disabled.
// Final action language is now generated by the rulebook decision layer.

export function getRecommendation() {
  return null;
}

export default getRecommendation;
